const fs=require('fs'); const path=require('path'); const crypto=require('crypto');
const CODE_EXT=new Set(['.js','.jsx','.ts','.tsx','.mjs','.cjs','.json','.md','.py','.mo','.rs','.go','.html','.css']);
function walk(dir,ignore=['node_modules','.git','dist','build','.next']){let out=[]; for(const ent of fs.readdirSync(dir,{withFileTypes:true})){ if(ignore.includes(ent.name)) continue; const p=path.join(dir,ent.name); if(ent.isDirectory()) out=out.concat(walk(p,ignore)); else if(CODE_EXT.has(path.extname(ent.name))) out.push(p);} return out;}
function hash(s){return crypto.createHash('sha256').update(s).digest('hex');}
function tokenize(s){return (s.toLowerCase().match(/[a-z0-9_.-]{2,}/g)||[]).filter(x=>!['const','let','var','function','return','import','from','export','class'].includes(x));}
function parseFile(file,root){const text=fs.readFileSync(file,'utf8'); const rel=path.relative(root,file); const exports=[...text.matchAll(/export\s+(?:default\s+)?(?:async\s+)?(?:function|class|const|let|var)\s+([A-Za-z0-9_]+)/g)].map(m=>m[1]); const funcs=[...text.matchAll(/(?:function\s+|const\s+|let\s+|var\s+)([A-Za-z0-9_]+)\s*(?:=\s*(?:async\s*)?\([^)]*\)\s*=>|\()/g)].map(m=>m[1]); const imports=[...text.matchAll(/(?:import .*? from\s+['"]([^'"]+)['"]|require\(['"]([^'"]+)['"]\))/g)].map(m=>m[1]||m[2]); return {file:rel,bytes:Buffer.byteLength(text),hash:hash(text),exports,functions:[...new Set(funcs)],imports:[...new Set(imports)],tokens:tokenize(text).slice(0,800),summary:text.slice(0,500)};}
function indexRepo(rootDir){const root=path.resolve(rootDir); const files=walk(root).map(f=>parseFile(f,root)); let packages={}; const pkg=path.join(root,'package.json'); if(fs.existsSync(pkg)){try{packages=JSON.parse(fs.readFileSync(pkg,'utf8'));}catch{}} const graph={nodes:files.map(f=>f.file),edges:[]}; const byBase=new Map(files.map(f=>[path.basename(f.file).replace(/\.[^.]+$/,''),f.file])); for(const f of files){for(const im of f.imports){let target=byBase.get(path.basename(im)); if(target) graph.edges.push({from:f.file,to:target,import:im});}} return {root,createdAt:new Date().toISOString(),fileCount:files.length,files,package:packages,dependencyGraph:graph};}
function semanticSearch(index,query,limit=10){const q=tokenize(query); const qset=new Set(q); const scored=index.files.map(f=>{let score=0; for(const t of f.tokens){ if(qset.has(t)) score+=2; for(const qt of q){ if(t.includes(qt)||qt.includes(t)) score+=0.25; }} for(const e of [...f.exports,...f.functions]) if(qset.has(e.toLowerCase())) score+=5; return {file:f.file,score:Number(score.toFixed(3)),exports:f.exports,functions:f.functions,summary:f.summary};}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,limit); return {query,results:scored};}
module.exports={indexRepo,semanticSearch};
