#!/usr/bin/env node
const http=require('http'); const {indexRepo,semanticSearch}=require('../engine/repo_intelligence'); const {buildCapsule}=require('../engine/capsule'); const {stagePermission}=require('../engine/permissions'); const {sandboxExecute}=require('../engine/sandbox'); const {migrateDownloads}=require('../engine/storage_engine'); const {loadConfig}=require('../engine/paths');
const tools=[
 {name:'nova_status',description:'Return NOVA Agent Council local status.',inputSchema:{type:'object',properties:{}}},
 {name:'repo_explorer',description:'Index a local repository with AST-lite signatures, imports, exports, and dependency graph.',inputSchema:{type:'object',properties:{path:{type:'string'}},required:['path']}},
 {name:'repo_semantic_search',description:'Search a previously supplied repo index conceptually using local token vectors.',inputSchema:{type:'object',properties:{index:{type:'object'},query:{type:'string'}},required:['index','query']}},
 {name:'create_capsule',description:'Create a local NOVA HTML capsule with manifest and receipt.',inputSchema:{type:'object',properties:{name:{type:'string'},title:{type:'string'},body:{type:'string'}}}},
 {name:'stage_app_permission',description:'Stage permission for external app action. Does not execute.',inputSchema:{type:'object',properties:{app:{type:'string'},action:{type:'string'},payload:{type:'object'}},required:['app','action']}},
 {name:'sandbox_execute',description:'Execute only allow-listed local validation commands, otherwise deny and receipt.',inputSchema:{type:'object',properties:{command:{type:'string'},cwd:{type:'string'}},required:['command']}},
 {name:'storage_migration_dryrun',description:'Preview Downloads migration to D vault with hash receipts.',inputSchema:{type:'object',properties:{}}},
 {name:'prepare_icp_deploy',description:'Stage ICP deployment packet and permission request.',inputSchema:{type:'object',properties:{canister:{type:'string'},path:{type:'string'}}}},
 {name:'prepare_hermes_edge_deploy',description:'Stage HERMES edge/web capsule deployment packet without exposing provider plumbing publicly.',inputSchema:{type:'object',properties:{capsulePath:{type:'string'}}}}
];
async function callTool(name,args={}){if(name==='nova_status') return {content:[{type:'text',text:JSON.stringify({version:'0.8.0',config:loadConfig()},null,2)}]}; if(name==='repo_explorer') return {content:[{type:'text',text:JSON.stringify(indexRepo(args.path),null,2)}]}; if(name==='repo_semantic_search') return {content:[{type:'text',text:JSON.stringify(semanticSearch(args.index,args.query),null,2)}]}; if(name==='create_capsule') return {content:[{type:'text',text:JSON.stringify(buildCapsule(args),null,2)}]}; if(name==='stage_app_permission') return {content:[{type:'text',text:JSON.stringify(stagePermission(args.app,args.action,args.payload||{}),null,2)}]}; if(name==='sandbox_execute') return {content:[{type:'text',text:JSON.stringify(sandboxExecute(args.command,args.cwd),null,2)}]}; if(name==='storage_migration_dryrun') return {content:[{type:'text',text:JSON.stringify(migrateDownloads({dryRun:true}),null,2)}]}; if(name==='prepare_icp_deploy') return {content:[{type:'text',text:JSON.stringify(stagePermission('icp_deploy','dfx deploy staging',args),null,2)}]}; if(name==='prepare_hermes_edge_deploy') return {content:[{type:'text',text:JSON.stringify(stagePermission('hermes_edge_deploy','edge capsule publish staging',args),null,2)}]}; throw new Error('unknown tool '+name)}
function handleRpc(req){if(req.method==='tools/list') return {tools}; if(req.method==='tools/call') return callTool(req.params.name,req.params.arguments||{}); return {jsonrpc:'2.0',id:req.id,error:{code:-32601,message:'Method not found'}}}
if(process.argv.includes('--http')){const cfg=loadConfig(); const server=http.createServer((req,res)=>{let body=''; req.on('data',d=>body+=d); req.on('end',async()=>{try{if(req.method==='GET'){res.end(JSON.stringify({name:'NOVA MCP Spine',tools:tools.map(t=>t.name)}));return} const rpc=JSON.parse(body||'{}'); const result=await handleRpc(rpc); res.setHeader('content-type','application/json'); res.end(JSON.stringify({jsonrpc:'2.0',id:rpc.id,result}));}catch(e){res.statusCode=500; res.end(JSON.stringify({error:e.message}))}})}); server.listen(cfg.mcp.port,cfg.mcp.host,()=>console.log(`NOVA MCP Spine listening on http://${cfg.mcp.host}:${cfg.mcp.port}`));}
module.exports={tools,callTool,handleRpc};
